import abc
from typing import AsyncGenerator, List, Optional, Dict, Any
from pydantic import BaseModel, Field

# ==========================================
# PYDANTIC SCHEMAS
# ==========================================

class ChatMessage(BaseModel):
    role: str = Field(..., description="Message role: 'system', 'user', or 'assistant'")
    content: str = Field(..., description="The textual content of the message")

class LLMStreamChunk(BaseModel):
    delta_text: str = Field(default="", description="Incremental text snippet generated by the LLM")
    finish_reason: Optional[str] = Field(default=None, description="Reason stream ended (e.g. 'stop', 'length')")
    usage: Optional[Dict[str, int]] = Field(default=None, description="Token usage stats if available in chunk")

class LLMResponse(BaseModel):
    content: str = Field(..., description="Complete text response from the model")
    finish_reason: str = Field(default="stop", description="Reason model stopped generating")
    input_tokens: int = Field(default=0, description="Tokens consumed in request prompt")
    output_tokens: int = Field(default=0, description="Tokens generated in response")
    provider_name: str = Field(..., description="Name of the provider that served this request")
    model_name: str = Field(..., description="Model ID used for response")

class ProviderHealthStatus(BaseModel):
    is_available: bool = Field(..., description="Whether provider is operational and reachable")
    provider_name: str = Field(..., description="Provider identifier (e.g., 'groq', 'anthropic', 'ollama')")
    current_model: str = Field(..., description="Active default model name")
    is_local: bool = Field(default=False, description="Whether this runs locally without API key requirements")
    available_models: List[str] = Field(default_factory=list, description="List of recognized or available models")
    error_message: Optional[str] = Field(default=None, description="Detailed error message if health check failed")

# ==========================================
# CUSTOM EXCEPTIONS
# ==========================================

class LLMException(Exception):
    """Base exception for LLM operations."""
    def __init__(self, message: str, provider_name: Optional[str] = None):
        super().__init__(message)
        self.message = message
        self.provider_name = provider_name

class ProviderUnavailableException(LLMException):
    """Raised when a requested provider is offline, unreachable, or missing credentials."""
    def __init__(self, provider_name: str, reason: str, actionable_instructions: str):
        full_msg = f"Provider '{provider_name}' unavailable: {reason}. Action required: {actionable_instructions}"
        super().__init__(full_msg, provider_name=provider_name)
        self.reason = reason
        self.actionable_instructions = actionable_instructions

class TokenLimitExceededException(LLMException):
    """Raised when context token count exceeds provider limit."""
    pass

# ==========================================
# ABSTRACT BASE PROVIDER
# ==========================================

class BaseLLMProvider(abc.ABC):
    """Abstract Base Class defining the unified interface for all LLM providers."""

    def __init__(self, model_name: str, api_key: Optional[str] = None, base_url: Optional[str] = None):
        self.model_name = model_name
        self.api_key = api_key
        self.base_url = base_url

    @property
    @abc.abstractmethod
    def provider_name(self) -> str:
        """Returns unique string identifier for the provider."""
        pass

    @abc.abstractmethod
    async def generate_stream(
        self,
        messages: List[ChatMessage],
        system_prompt: Optional[str] = None,
        temperature: float = 0.7,
        max_tokens: int = 2048,
    ) -> AsyncGenerator[LLMStreamChunk, None]:
        """Asynchronously stream response chunks from LLM."""
        pass

    @abc.abstractmethod
    async def generate_complete(
        self,
        messages: List[ChatMessage],
        system_prompt: Optional[str] = None,
        temperature: float = 0.7,
        max_tokens: int = 2048,
    ) -> LLMResponse:
        """Asynchronously return complete LLM response."""
        pass

    @abc.abstractmethod
    async def check_health(self) -> ProviderHealthStatus:
        """Probe provider connection status and credentials validity."""
        pass
